# Generated by Django 2.2.24 on 2022-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                verbose_name='Номер владельца'
            ),
        ),
    ]
