# Generated by Django 2.2.24 on 2022-03-20 07:30

from django.db import migrations


def set_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(
            owner=flat.owner,
            phone_number=flat.owners_phonenumber,
            normalaized_phone_number=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20220320_1030'),
    ]

    operations = [
        migrations.RunPython(set_owners),
    ]
