# Generated by Django 2.2.24 on 2022-03-20 07:30

from django.db import migrations


def add_owner_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        owner, _ = Owner.objects.get_or_create(
            owner=flat.owner,
            phone_number=flat.owners_phonenumber,
        )
        owner.apartments_in_property.add(flat)
        owner.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0009_auto_20220320_1030'),
    ]

    operations = [
        migrations.RunPython(add_owner_flats),
    ]
