# Generated by Django 2.2.24 on 2022-03-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220328_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='property.Owner', verbose_name='ФИО владельца'),
        ),
    ]
