# Generated by Django 2.2.24 on 2022-03-29 06:26

from django.db import migrations


def add_owner_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner_record in Owner.objects.all().iterator():
        for property_record in owner_record.apartments_in_property.all().iterator():
            flat_record = Flat.objects.filter(pk=property_record.pk)
            flat_record.update(
                owner_id=owner_record.pk
            )


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0012_flat_owner')

    ]

    operations = [

        migrations.RunPython(add_owner_flats),
    ]

