# Generated by Django 2.2.24 on 2022-03-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220329_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(default='00000', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='property.Owner', verbose_name='ФИО владельца'),
        ),
    ]
