# Generated by Django 2.2.24 on 2022-03-31 05:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20220330_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='property.Owner', verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='normalaized_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='0', max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
